### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by OpenSourceDevelop** [RuggedScience/atprogram-gui#2]
[ERROR] Could not set device properties. Make sure you have selected correct device and interface, and that the hardware connections are correct.
Firmware check OK

in the Production Tab / Memories
used atbackend.exe from avr studio 7.0.2.3.9 
with atmel - ice 

if i do it by hand:
atprogram -t atmelice -i ISP -d atmega32u4 program -f c:\Navtec.hex
atprogram -t atmelice -i ISP -d atmega32u4 write -fs --values FFD8FB
it works fine

by the way nice program! :)

**Comment by timothy-lassiter** [comment]
@OpenSourceDevelop - Sorry for the slow response... I should really "watch" my own repos. Can you upload or paste the debug output? Are there any special steps to reproduce this? I also use the Atmel-ICE and atmega32u4 so hopefully I can reproduce it here. 

Also, thanks! I find it much better than having to open AS7 just to flash a board...

**Comment by OpenSourceDevelop** [comment]
Hello,

no problem, the debug output is not really helpfull:
"atprogram.exe -v -t atmelice -i ISP -d atmega32u4 program --verify -c -fl -f C:/Navtec.hex
[DEBUG] Starting execution of "program"
[DEBUG] Starting process 'C:\Program Files (x86)\RuggedScience\atprogram\atbackend\atbackend.exe'
[DEBUG] Connecting to TCP:127.0.0.1:56110
[INFO] Connected to atmelice, fw version: 1.29
[INFO] Firmware check OK
[ERROR] Could not set device properties. Make sure you have selected correct device and interface, and that the hardware connections are correct.
Firmware check OK
"

not anything apecial just the Atmel-ICE with ISP an a atmega32u4

as you can see by hand in two steps it will work. did they changed the commands? or the order? why is there a tcp connection?

**Comment by timothy-lassiter** [comment]
@OpenSourceDevelop ,

It looks like it is actually using atbackend from 'C:\Program Files (x86)\RuggedScience\atprogram\atbackend\atbackend.exe'.  By default atprogram installs with atprogram-gui. You can uninstall atprogram-gui and reinstall it without atprogram to use your AS7 version. Unfortunately the QtInstallerFramework won't let you just remove atprogram since it's an offline installer. If you just want to use the atprogram version that installed with atprogram-gui, you just need to reset the cache. The installer will also install an atpackmanager icon, just run that, and click 'Advanced->Reset Cache'. Unfortunately atprogram doesn't like being "moved around". Hopefully one of these options gets everything working for you.

**Comment by timothy-lassiter** [comment]
@OpenSourceDevelop ,

I updated atprogram-gui to prioritize atbackend from Atmel Studio. I think it makes sense that if the user already has Atmel Studio installed it should use that atpackmanager. I also updated the installer to reset the cache for atpackmanager during the install. Hopefully this will help avoid issues like you experienced.

**Comment by OpenSourceDevelop** [comment]
Hello Timothy,

i would like to test it, do you have a link to the new installer?

Thank you
Norman

________________________________
Von: Timothy Lassiter <notifications@github.com>
Gesendet: Donnerstag, 10. Oktober 2019 19:10
An: RuggedScience/atprogram-gui <atprogram-gui@noreply.github.com>
Cc: OpenDev <nkarlemobile@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [RuggedScience/atprogram-gui] little bug (#2)


@OpenSourceDevelop<https://github.com/OpenSourceDevelop> ,

I updated atprogram-gui to prioritize atbackend from Atmel Studio. I think it makes sense that if the user already has Atmel Studio installed it should use that atpackmanager. I also updated the installer to reset the cache for atpackmanager during the install. Hopefully this will help avoid issues like you experienced.

**Comment by timothy-lassiter** [comment]
That would be great. I posted it under the releases. Link below.

https://github.com/RuggedScience/atprogram-gui/releases/tag/v.1.1.3

Let me know what you find.

**Comment by OpenSourceDevelop** [comment]
Just reinstalled it (deled the folder first). Works just fine. But you don’t get a start programs entry, but this is cosmetic.



nice feature would be set up profiles, for avr projects or so 😉





but thank you very much!

________________________________
Von: Timothy Lassiter <notifications@github.com>
Gesendet: Freitag, 11. Oktober 2019 13:01
An: RuggedScience/atprogram-gui <atprogram-gui@noreply.github.com>
Cc: OpenDev <nkarlemobile@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [RuggedScience/atprogram-gui] little bug (#2)


That would be great. I posted it under the releases. Link below.

https://github.com/RuggedScience/atprogram-gui/releases/tag/v.1.1.3

Let me know what you find.

**Comment by timothy-lassiter** [comment]
Glad that fixed it. You are no longer getting the PackManager start menu entry? That's strange... I like the profiles idea. You're talking just a way to switch between which backend to use?
